p1: p1.c
	gcc $< -o $@

p2: p2.c
	gcc $< -o $@

p3: p3.c
	gcc $< -o $@

p4: p4.c
	gcc $< -o $@

p4-1: p4-1.c
	gcc $< -o $@

p5: p5.c
	gcc $< -o $@

p6-1: p6-1.c
	gcc $< -o $@

p6-2: p6-2.c
	gcc $< -o $@
